export GOROOT=/usr/local/go;
export GOPATH=/home/jinathy/go;
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH;
export GOOS=windows;
export GOARCH=386;
export CGO_ENABLED=1;
export CXX=i686-w64-mingw32-g++;
export CC=i686-w64-mingw32-gcc;
go build -buildmode=c-shared -o ../tangoenterprise/Expert1.Tango/bin/Debug/cloud_sql_proxy_x86.dll ./lib/cloud_sql_proxy