// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proxy-status/proxy-status.proto

package proxy_status

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProxyStatusRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyStatusRequest) Reset()         { *m = ProxyStatusRequest{} }
func (m *ProxyStatusRequest) String() string { return proto.CompactTextString(m) }
func (*ProxyStatusRequest) ProtoMessage()    {}
func (*ProxyStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc660c45543b2f5, []int{0}
}

func (m *ProxyStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyStatusRequest.Unmarshal(m, b)
}
func (m *ProxyStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyStatusRequest.Marshal(b, m, deterministic)
}
func (m *ProxyStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyStatusRequest.Merge(m, src)
}
func (m *ProxyStatusRequest) XXX_Size() int {
	return xxx_messageInfo_ProxyStatusRequest.Size(m)
}
func (m *ProxyStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyStatusRequest proto.InternalMessageInfo

func (m *ProxyStatusRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProxyStatusRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ProxyStatusRequest) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ProxyStatusReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyStatusReply) Reset()         { *m = ProxyStatusReply{} }
func (m *ProxyStatusReply) String() string { return proto.CompactTextString(m) }
func (*ProxyStatusReply) ProtoMessage()    {}
func (*ProxyStatusReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc660c45543b2f5, []int{1}
}

func (m *ProxyStatusReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyStatusReply.Unmarshal(m, b)
}
func (m *ProxyStatusReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyStatusReply.Marshal(b, m, deterministic)
}
func (m *ProxyStatusReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyStatusReply.Merge(m, src)
}
func (m *ProxyStatusReply) XXX_Size() int {
	return xxx_messageInfo_ProxyStatusReply.Size(m)
}
func (m *ProxyStatusReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyStatusReply.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyStatusReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ProxyStatusRequest)(nil), "ProxyStatusRequest")
	proto.RegisterType((*ProxyStatusReply)(nil), "ProxyStatusReply")
}

func init() {
	proto.RegisterFile("proxy-status/proxy-status.proto", fileDescriptor_2bc660c45543b2f5)
}

var fileDescriptor_2bc660c45543b2f5 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2f, 0x28, 0xca, 0xaf,
	0xa8, 0xd4, 0x2d, 0x2e, 0x49, 0x2c, 0x29, 0x2d, 0xd6, 0x47, 0xe6, 0xe8, 0x15, 0x14, 0xe5, 0x97,
	0xe4, 0x2b, 0x85, 0x71, 0x09, 0x05, 0x80, 0x44, 0x83, 0xc1, 0x82, 0x41, 0xa9, 0x85, 0xa5, 0xa9,
	0xc5, 0x25, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c,
	0x41, 0x60, 0xb6, 0x90, 0x18, 0x17, 0x1b, 0x44, 0xa7, 0x04, 0x13, 0x58, 0x14, 0xca, 0x13, 0x12,
	0xe1, 0x62, 0x4d, 0x2d, 0x2a, 0xca, 0x2f, 0x92, 0x60, 0x06, 0x0b, 0x43, 0x38, 0x4a, 0x42, 0x5c,
	0x02, 0x28, 0xe6, 0x16, 0xe4, 0x54, 0x1a, 0x79, 0x72, 0x71, 0x23, 0x89, 0x09, 0x59, 0x71, 0xf1,
	0x05, 0xa7, 0x96, 0x20, 0x8b, 0x08, 0xeb, 0x61, 0xba, 0x45, 0x4a, 0x50, 0x0f, 0xdd, 0x20, 0x25,
	0x86, 0x24, 0x36, 0xb0, 0xeb, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1d, 0xb4, 0xa3, 0x9a,
	0xe0, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProxyStatusClient is the client API for ProxyStatus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProxyStatusClient interface {
	SetProxyStatus(ctx context.Context, in *ProxyStatusRequest, opts ...grpc.CallOption) (*ProxyStatusReply, error)
}

type proxyStatusClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyStatusClient(cc grpc.ClientConnInterface) ProxyStatusClient {
	return &proxyStatusClient{cc}
}

func (c *proxyStatusClient) SetProxyStatus(ctx context.Context, in *ProxyStatusRequest, opts ...grpc.CallOption) (*ProxyStatusReply, error) {
	out := new(ProxyStatusReply)
	err := c.cc.Invoke(ctx, "/ProxyStatus/SetProxyStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyStatusServer is the server API for ProxyStatus service.
type ProxyStatusServer interface {
	SetProxyStatus(context.Context, *ProxyStatusRequest) (*ProxyStatusReply, error)
}

// UnimplementedProxyStatusServer can be embedded to have forward compatible implementations.
type UnimplementedProxyStatusServer struct {
}

func (*UnimplementedProxyStatusServer) SetProxyStatus(ctx context.Context, req *ProxyStatusRequest) (*ProxyStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetProxyStatus not implemented")
}

func RegisterProxyStatusServer(s *grpc.Server, srv ProxyStatusServer) {
	s.RegisterService(&_ProxyStatus_serviceDesc, srv)
}

func _ProxyStatus_SetProxyStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProxyStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyStatusServer).SetProxyStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProxyStatus/SetProxyStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyStatusServer).SetProxyStatus(ctx, req.(*ProxyStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProxyStatus_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ProxyStatus",
	HandlerType: (*ProxyStatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetProxyStatus",
			Handler:    _ProxyStatus_SetProxyStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proxy-status/proxy-status.proto",
}
